-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles Table (extends auth.users)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  name TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'user',
  plan TEXT DEFAULT 'free',
  status TEXT DEFAULT 'active',
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. URLs Table
CREATE TABLE public.urls (
  id TEXT PRIMARY KEY, -- Short code (e.g., nanoid)
  original_url TEXT NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  domain_id TEXT, -- Optional reference to domains table
  domain_name TEXT, -- Denormalized for easier access
  clicks INTEGER DEFAULT 0,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Domains Table
CREATE TABLE public.domains (
  id TEXT PRIMARY KEY, -- nanoid
  name TEXT UNIQUE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending', -- pending, verified, failed
  verification_token TEXT,
  verification_type TEXT DEFAULT 'txt',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. API Keys Table
CREATE TABLE public.api_keys (
  id TEXT PRIMARY KEY, -- nanoid
  key TEXT UNIQUE NOT NULL,
  name TEXT,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_email TEXT, -- Denormalized
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tasks Table
CREATE TABLE public.tasks (
  id TEXT PRIMARY KEY, -- nanoid
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  completed BOOLEAN DEFAULT FALSE,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Clicks Table (Analytics)
CREATE TABLE public.clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url_id TEXT REFERENCES public.urls(id) ON DELETE CASCADE,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  user_agent TEXT,
  referer TEXT,
  country TEXT DEFAULT 'Unknown',
  city TEXT DEFAULT 'Unknown',
  device TEXT DEFAULT 'Unknown',
  browser TEXT DEFAULT 'Unknown',
  os TEXT DEFAULT 'Unknown'
);

-- 7. Rate Limits Table (Optional, can use Redis or similar in prod, but table works for simple use)
CREATE TABLE public.rate_limits (
  api_key TEXT PRIMARY KEY,
  count INTEGER DEFAULT 0,
  reset_at TIMESTAMPTZ
);

-- Row Level Security (RLS) Policies

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.urls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clicks ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Users can view their own profile" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

-- URLs Policies
CREATE POLICY "Users can view their own URLs" 
ON public.urls FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own URLs" 
ON public.urls FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own URLs" 
ON public.urls FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own URLs" 
ON public.urls FOR DELETE 
USING (auth.uid() = user_id);

-- Domains Policies
CREATE POLICY "Users can view their own domains" 
ON public.domains FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own domains" 
ON public.domains FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own domains" 
ON public.domains FOR DELETE 
USING (auth.uid() = user_id);

-- API Keys Policies
CREATE POLICY "Users can view their own API keys" 
ON public.api_keys FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own API keys" 
ON public.api_keys FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own API keys" 
ON public.api_keys FOR DELETE 
USING (auth.uid() = user_id);

-- Tasks Policies
CREATE POLICY "Users can view their own tasks" 
ON public.tasks FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own tasks" 
ON public.tasks FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own tasks" 
ON public.tasks FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own tasks" 
ON public.tasks FOR DELETE 
USING (auth.uid() = user_id);

-- Clicks Policies
-- Users can view clicks for their URLs
CREATE POLICY "Users can view clicks for their URLs" 
ON public.clicks FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.urls 
    WHERE public.urls.id = public.clicks.url_id 
    AND public.urls.user_id = auth.uid()
  )
);

-- Function to handle new user signup (Trigger)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, avatar_url)
  VALUES (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
